### ISSUE TITLE
Feature request: Installation of packages

### ISSUE THREAD

**Issue by thewhitetulip** [limetext/backend#116] opened 2016-08-15 08:00 UTC
We can provide a command to install packages like Go language itself does.

When we do a `go get`, it'll run git clone in the backend. While installing ST3 plugins, you have to clone the plugin into a specific folder, we can automate that with a commandline utility which comes by default in Lime.

**Comment by erbridge** [comment] 2016-08-16 11:02
There's a thing called Package Control for ST3 that automates a lot of that stuff, but I believe making a package manager first class in Lime would be a good thing.

**Comment by thewhitetulip** [comment] 2016-08-16 12:29
@erbridge The beauty is that we can store the packages in github, give a repo name to link to the package name

and fetch and install the packages from github, so we don't need to have a website storing packages :-)

**Comment by erbridge** [comment] 2016-08-16 12:49
Exactly. See https://packagecontrol.io.

**Comment by thewhitetulip** [comment] 2016-08-16 15:20
If ST already had this feature then why do we need to manually install packages?

**Comment by erbridge** [comment] 2016-08-16 15:38
In ST3, you first install Package Control, then use the Command Palette to install packages. Ideally Lime would be able to do it without Package Control, IMO.

> If ST already had this feature then why do we need to manually install packages?

I'm not sure what you're referring to.

**Comment by thewhitetulip** [comment] 2016-08-16 15:55
> you first install Package Control

So basically you have to install the package manager manually, after which you can use command palette.

Lime would have this feature by default, that's a great news. I honestly feel that softwares these days are platforms of their own, so having a better UX/UI to the part which makes it a platform is very important!

I wanted to install the Go language plugin for sublime, I did not find a package manager in st3. That's what I was referring to.

**Comment by erbridge** [comment] 2016-08-16 15:56
Ah. Get GoSublime using Package Control.

**Comment by thewhitetulip** [comment] 2016-08-16 16:04
Yep, I want to contribute more code, at a loss at what to write :-) shall I build this package manager? or build more commands?

**Comment by erbridge** [comment] 2016-08-16 16:09
This is very low priority. Higher priority is making the QML frontend work. Failing that, you could look at commands, but leave this until later.

**Comment by thewhitetulip** [comment] 2016-08-16 16:10
To be honest, I tried looking into the front end and I couldn't understand anything :D

**Comment by zoli** [comment] 2016-08-16 17:18
This is duplicate of https://github.com/limetext/lime/issues/542.

**Comment by thewhitetulip** [comment] 2016-08-17 03:43
@zoli We can close that issue, because it should be in the backend repo right?

Also did you get a chance of looking at the issue migration script?

**Comment by zoli** [comment] 2016-08-17 06:13
> it should be in the backend repo right?

I don't think so, It's not related to backend. If we are going to have a package manager we'll have a separate repository for it and until then lime meta project is a proper place for gathering ideas and discussing features.

> Also did you get a chance of looking at the issue migration script?

Not yet.

**Comment by thewhitetulip** [comment] 2016-08-17 07:13
I thought it'd be a part of the backend.

**Closed** 2016-08-18 18:16 UTC
Labels: enhancement
